name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint & Typecheck
        run: |
          ruff check .
          black --check .
          mypy src
      - name: Tests
        run: |
          pytest -q

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        run: terraform fmt -recursive -check
      - name: Terraform validate (staging)
        working-directory: infra/terraform/envs/staging
        run: |
          terraform init -backend=false
          terraform validate
      - name: Terraform validate (prod)
        working-directory: infra/terraform/envs/prod
        run: |
          terraform init -backend=false
          terraform validate
